version: '3.4'
name: "services-service"

services:
    
  services-api:
    build:
      context: ./
      dockerfile: ./api_container/Dockerfile
    ports:
      - "${EXTERNAL_SERVICES_API_PORT}:${SERVICES_API_PORT}"
    restart: unless-stopped
    networks:
      - my-services-network

networks:
  my-services-network:
    external: true
